spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products?useSSL=false&serverTimezone=UTC
    username: root
    password: Azerty12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
app:
  # Secret key comes from https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb

