spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products?useSSL=false&serverTimezone=UTC
    username: root
    password: Azerty12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

